const AFFILIATE_TAG = "crawfishboilc-20";
const amazonLink = (query) => `https://www.amazon.com/s?k=${encodeURIComponent(query)}&tag=${AFFILIATE_TAG}`;

export const EQUIPMENT = [
  { name: "80-Qt Boiling Pot w/ Basket", price: "$89-$140", desc: "The workhorse. Get one with a strainer basket and lid. 80-qt handles 30-40 lbs of crawfish.", tier: "essential" },
  { name: "High-Pressure Propane Burner", price: "$50-$100", desc: "You need serious BTUs. Look for 100,000+ BTU burners. Bayou Classic and King Kooker are solid.", tier: "essential" },
  { name: "Propane Tank (20 lb)", price: "$20-$40", desc: "A full tank will last you through most boils. Always have a backup if you're doing 60+ lbs.", tier: "essential" },
  { name: "Crawfish Paddle", price: "$15-$30", desc: "Long wooden or metal paddle for stirring. Don't use a regular spoon -- you need reach.", tier: "essential" },
  { name: "Purge Tub / Washtub", price: "$15-$40", desc: "Dedicated container for purging. A large plastic washtub, kiddie pool, or second cooler works. Keep separate from your drink cooler.", tier: "essential" },
  { name: "Heavy Duty Gloves", price: "$10-$20", desc: "Heat-resistant gloves for handling the basket. Silicone or leather -- not latex.", tier: "recommended" },
  { name: "Outdoor Folding Table (6ft)", price: "$40-$60", desc: "Cover it with butcher paper. This is where the magic happens. Two tables for 30+ people.", tier: "recommended" },
  { name: "Large Cooler (100+ Qt)", price: "$50-$120", desc: "For drinks and ice. A second cooler for purging is ideal but a washtub works too.", tier: "recommended" },
  { name: "Garden Hose + Spray Nozzle", price: "$15-$25", desc: "You need running water for purging -- plan 3-4 full water changes. If your boil spot is far from a spigot, bring a long hose.", tier: "recommended" },
  { name: "Thermometer (Clip-on)", price: "$10-$20", desc: "Know your water temp. You want a rolling boil at 212F before dropping crawfish.", tier: "nice-to-have" },
  { name: "Table Clips / Clamps", price: "$8-$15", desc: "Holds butcher paper down in the wind. Binder clips work in a pinch.", tier: "nice-to-have" },
  { name: "Folding Chairs", price: "$15-$25 each", desc: "People stand to eat but want to sit between batches. Budget 1 chair per 2-3 guests.", tier: "nice-to-have" },
];

export const EQUIPMENT_LINKS = {
  "80-Qt Boiling Pot w/ Basket": amazonLink("80 qt crawfish boiling pot basket"),
  "High-Pressure Propane Burner": amazonLink("high pressure propane burner outdoor cooking"),
  "Propane Tank (20 lb)": amazonLink("20 lb propane tank"),
  "Crawfish Paddle": amazonLink("crawfish boil paddle long wooden"),
  "Purge Tub / Washtub": amazonLink("large plastic washtub outdoor"),
  "Heavy Duty Gloves": amazonLink("heat resistant silicone gloves cooking"),
  "Outdoor Folding Table (6ft)": amazonLink("6ft folding table outdoor"),
  "Large Cooler (100+ Qt)": amazonLink("100 qt cooler"),
  "Garden Hose + Spray Nozzle": amazonLink("garden hose spray nozzle"),
  "Thermometer (Clip-on)": amazonLink("clip on pot thermometer cooking"),
  "Table Clips / Clamps": amazonLink("tablecloth clips outdoor"),
  "Folding Chairs": amazonLink("folding chairs outdoor set"),
};

export const RECIPES = [
  { id: "classic", title: "Classic Louisiana Crawfish Boil", time: "60 min", difficulty: "Easy", category: "boil",
    desc: "The traditional backyard boil. Seasoned water, perfect timing, a long soak, and dumped on newspaper.",
    steps: ["Purge crawfish: dump into a cooler or large basin, run clean water over them until it runs clear (3-4 water changes). Remove any dead ones.", "Fill pot halfway with water. Add a cup of white vinegar.", "Add boil seasoning (powder + liquid), halved lemons and oranges (squeeze juice in first), whole garlic heads, halved onions, celery stalks. Bring to rolling boil, cook 10-15 min.", "Add potatoes and sausage. Boil until potatoes are almost fork-tender, about 10 min.", "Add corn. Boil 5 more minutes.", "Add purged crawfish at a rolling boil. Cover, return to boil, cook 3-5 minutes.", "Kill the fire. Add frozen corn or ice to drop temp. Soak 15-20 min minimum.", "Lift basket, dump on newspaper-covered table. Eat immediately."],
    tip: "The soak is where flavor gets absorbed. 15 min = mild, 20-25 min = well-seasoned, 30+ = spicy." },
  { id: "viet-cajun", title: "Viet-Cajun Crawfish Boil", time: "60 min", difficulty: "Medium", category: "boil",
    desc: "Houston/NOLA fusion style. Standard boil with a garlic butter citrus sauce tossed after.",
    steps: ["Boil crawfish using the classic method -- purge, season water, boil 3-5 min, soak 15-20 min.", "Make sauce: melt 1 stick butter per 3 lbs crawfish. Add minced garlic, cook 2 min.", "Add 2 tbsp Cajun seasoning, 1 tbsp paprika, juice of 2 lemons, 1 tbsp sugar, 2 tbsp liquid boil concentrate.", "Optional: add 1-2 tbsp sriracha or sambal.", "Drain crawfish, toss in batches into butter sauce.", "Dump into bags or bowls. Let sit 5 min.", "Serve with French bread."],
    tip: "Some shops add lemongrass and fish sauce -- experiment and find your style." },
  { id: "garlic-butter", title: "Garlic Butter Crawfish", time: "15 min", difficulty: "Easy", category: "boil",
    desc: "Quick post-boil finisher. Toss a portion in garlic butter for a decadent upgrade.",
    steps: ["Melt 2 sticks butter over medium heat.", "Add minced garlic (8-10 cloves), cook 2 min.", "Add boil seasoning, lemon juice, hot sauce.", "Toss in 3-5 lbs warm boiled crawfish. Stir to coat.", "Cover, sit 5 min off heat.", "Serve with butter pooled at bottom. French bread mandatory."],
    tip: "Works best as a finisher for a portion of your boil, not the whole batch." },
  { id: "etouffee", title: "Crawfish Etouffee", time: "45 min", difficulty: "Medium", category: "cajun",
    desc: "Crawfish tails in a rich, roux-based gravy over rice. A cornerstone of Louisiana cooking.",
    steps: ["Make roux: melt 4 tbsp butter, whisk in 4 tbsp flour. Stir 5-7 min until golden/copper.", "Add holy trinity: diced onion, celery, bell pepper. Cook 8 min.", "Add garlic, cook 1 min. Stir in Cajun seasoning, cayenne, salt, pepper.", "Add 2 cups stock. Stir smooth. Simmer 20-30 min.", "Add 1 lb crawfish tails (and fat). Cook 5 min.", "Finish with green onions, parsley, pat of butter. Serve over rice."],
    tip: "The crawfish fat (yellow stuff from heads) is where the deep flavor lives." },
  { id: "monica", title: "Crawfish Monica", time: "30 min", difficulty: "Easy", category: "cajun",
    desc: "The legendary Jazz Fest creamy crawfish pasta. Rotini, crawfish tails, Creole seasoning, cream sauce.",
    steps: ["Cook 1/2 lb rotini. Drain, rinse, drain again.", "Melt 4 tbsp butter. Saute onion and garlic 3 min.", "Add 1 lb crawfish tails and 1 cup half-and-half. Saute until bubbly.", "Season with Creole seasoning -- pinch at a time, tasting.", "Cook 5-10 min until sauce thickens.", "Toss in pasta. Low heat 10 min, stirring often. Serve immediately."],
    tip: "The original uses rotini -- spirals catch the sauce. No cheese in the original recipe." },
  { id: "fettuccine", title: "Crawfish Fettuccine", time: "35 min", difficulty: "Easy", category: "cajun",
    desc: "The cheesy, indulgent cousin of Crawfish Monica. Fettuccine in a Velveeta cream sauce.",
    steps: ["Cook 1 lb fettuccine. Drain, set aside.", "Melt 4 tbsp butter. Saute onion, bell pepper, celery 5-7 min.", "Add garlic 2 min. Add 1 lb crawfish tails, Cajun seasoning. Cook 2-3 min.", "Sprinkle 2 tbsp flour, stir 1 min. Add 1 cup half-and-half.", "Add 8 oz Velveeta, 1/4 cup sour cream, 1/4 cup Parmesan. Stir until melted.", "Fold in pasta and green onions. Serve hot."],
    tip: "Yes, it uses Velveeta. The processed cheese makes the sauce silky. Not the time for fancy cheese." },
  { id: "bisque", title: "Crawfish Bisque", time: "2+ hrs", difficulty: "Hard", category: "cajun",
    desc: "The crown jewel. Rich roux-based soup with stuffed crawfish heads. Labor-intensive, worth it.",
    steps: ["Clean 3-4 dozen crawfish heads. Set aside.", "Make stuffing: saute trinity, add chopped tails, breadcrumbs, Cajun seasoning, egg.", "Stuff heads, bake 350F for 15-20 min.", "Make dark roux (peanut butter color), 20-25 min.", "Add trinity, cook 10 min. Add 6-8 cups stock, seasonings. Simmer 45 min.", "Add tails and stuffed heads. Simmer 15 min.", "Finish with green onions, parsley. Serve over rice."],
    tip: "This is an all-day project. Save shells and heads from a boil to make stock." },
  { id: "pie", title: "Crawfish Pie", time: "60 min", difficulty: "Medium", category: "cajun",
    desc: "Savory pie with creamy seasoned crawfish filling in flaky crust. Great for leftover tail meat.",
    steps: ["Press bottom pie crust into 9-inch dish.", "Saute trinity in butter 8 min. Add garlic 1 min.", "Add 3 tbsp flour, stir 2 min. Add cream and stock, stir until thick.", "Season, fold in 1 lb tails and green onions. Remove from heat.", "Pour into crust. Cover with top crust, crimp, cut slits.", "Bake 375F 35-40 min until golden. Rest 10 min."],
    tip: "If using leftover boil tail meat, cut Cajun seasoning in half -- it's already seasoned." },
  { id: "poboy", title: "Fried Crawfish Po'Boy", time: "25 min", difficulty: "Easy", category: "cajun",
    desc: "Crispy fried crawfish tails on French bread. A New Orleans classic.",
    steps: ["Set up breading: seasoned flour, buttermilk, seasoned cornmeal/corn flour.", "Pat 1 lb tails dry. Season with Cajun seasoning.", "Dredge in flour, dip in buttermilk, coat in cornmeal.", "Fry at 350-375F, 2-3 min until golden. Drain.", "Toast French bread. Spread mayo or remoulade.", "Layer lettuce, tomato, pickles. Pile on crawfish."],
    tip: "Corn flour (not cornmeal) gives the crispiest coating. Zatarain's Fish Fri works great." },
];

export const TIPS = [
  { title: "Purge Your Crawfish", body: "Dump into a cooler, run clean water over them, change 3-4 times until clear. Remove dead ones (straight tails). Let sit in clean water an hour if you have time." },
  { title: "Season the Water First", body: "Seasonings, lemons, oranges, garlic, onions boiling 10-15 min before anything else. Use both powder and liquid concentrate for best results." },
  { title: "Add Vinegar to the Pot", body: "A cup of white distilled vinegar makes shells easier to peel and cuts the lingering smell. Game changer for indoor boils." },
  { title: "Don't Overcook", body: "3-5 min of actual boiling after water returns to rolling boil. Bigger crawfish go longer. Bright red + floating = done. The soak does the rest." },
  { title: "The Soak Is Everything", body: "Kill heat, add ice/frozen corn. Sit 15-30 min. When they start sinking, they've absorbed all they can." },
  { title: "Plan 3 lbs Per Person", body: "Heavy eaters: 5+ lbs. Light: 2 lbs. Budget 3 as baseline. Takes 6-8 lbs whole crawfish to get 1 lb tail meat." },
  { title: "Check Your Crawfish", body: "Most should be alive and active before buying. Straight tails after cooking = dead going in. Toss those." },
  { title: "Save the Leftovers", body: "Peel while warm. Store tails 2-3 days in fridge. Freeze heads/shells for stock. The fat is liquid gold for etouffee." },
  { title: "Use Oranges Too", body: "Oranges add sweetness that balances heat. Squeeze juice in first, toss halves in. Some use grapefruit -- citrus breaks down shells." },
];

export const SAFETY_CHECKLIST = [
  { id: "outdoor", label: "Boil is set up outdoors", desc: "Never use a propane burner indoors, in a garage, or under a carport. Open air only.", severity: "critical" },
  { id: "stable", label: "Burner is on flat, stable ground", desc: "Level surface away from structures, fences, and overhangs. At least 10 ft from anything flammable.", severity: "critical" },
  { id: "extinguisher", label: "Fire extinguisher nearby", desc: "Keep a Class B extinguisher rated for grease/propane within arm's reach. Know how to use it.", severity: "critical" },
  { id: "tank", label: "Propane tank inspected", desc: "Check for dents, rust, and bulges. Verify the date stamp — tanks expire 12 years from manufacture. Sniff around the valve for rotten-egg smell before connecting.", severity: "critical" },
  { id: "hose", label: "Hose & regulator in good shape", desc: "Inspect the rubber hose for cracks, dry rot, or soft spots. Check that the regulator isn't damaged. Replace any worn parts — they're cheap, burns aren't.", severity: "critical" },
  { id: "leaktest", label: "Soap bubble leak test done", desc: "Mix dish soap and water, brush it on every fitting — tank valve, regulator, hose connections. Open the valve slowly. Bubbles = leak. Tighten or replace, then retest.", severity: "critical" },
  { id: "kidsaway", label: "Kids & pets kept 10+ ft away", desc: "Set a clear boundary. Hot water, steam, and propane are all serious hazards for little ones.", severity: "warning" },
  { id: "gloves", label: "Heat-resistant gloves ready", desc: "Heavy-duty silicone or leather gloves for lifting baskets and handling the pot. No bare hands.", severity: "warning" },
  { id: "shoes", label: "Wearing closed-toe shoes", desc: "No sandals or flip-flops near boiling water. Spills happen. Protect your feet.", severity: "warning" },
  { id: "neverleave", label: "Plan to never leave burner unattended", desc: "Someone watches the flame at all times. Wind can blow it out and leak propane.", severity: "critical" },
  { id: "dontmove", label: "Won't move pot while full", desc: "A full 80-qt pot weighs 100+ lbs. Turn off burner and let it cool before any moving.", severity: "warning" },
  { id: "firstaid", label: "First aid kit accessible", desc: "Burn gel, bandages, and clean water nearby. Know where the nearest ER is just in case.", severity: "info" },
  { id: "phone", label: "Phone charged and nearby", desc: "Keep your phone close for emergencies. 911 first, then deal with the boil.", severity: "info" },
  { id: "overfill", label: "Pot is not overfilled", desc: "Leave 4-6 inches at the top. Crawfish displace water and can cause dangerous boil-overs.", severity: "warning" },
];
